- id: create-bats-readme
  name: Create Bats README.md
  description: Sysdig opinionated bats README creator
  entry: create-bats-docs
  language: python

- id: conftest-check
  name: Conftest test
  description: Sysdig opinionated conftest validation
  entry: pre_commit_hooks/conftest-check.sh
  language: script

- id: create-patch-files
  name: Create Patch Files
  description: Create upstream patch files
  entry: create-patch-files
  language: python
  pass_filenames: false
  always_run: true
